[mgr]
show_hidden = true

[opener]
edit = [
  { run = 'hx "$@"', block = true, cwd = "git rev-parse --show-toplevel || pwd" },
]
open = [
  { run = 'glow --tui "$@"', block = true, for = "text/markdown" },
  { run = 'hx "$@"', block = true, cwd = "git rev-parse --show-toplevel || pwd" },
]
