import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]

padding.x = 15
padding.y = 20

decorations = "Full"
decorations_theme_variant = "Dark"

title = "Terminal"



[font]

normal.family = "FiraCode Nerd Font"
bold.family = "FiraCode Nerd Font"
italic.family = "FiraCode Nerd Font"
bold_italic.family = "FiraCode Nerd Font"

size = 14.0

[cursor]

style.blinking = "On"
