theme = "catppuccin_mocha"

[editor]
mouse = false
bufferline = "multiple"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "file-encoding"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.indent-guides]
render = true

[keys.normal."space"]
"." = ":format"
"q" = ":bc"

[keys.normal]
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"

[editor.soft-wrap]
enable = true

[editor.lsp]
display-progress-messages = true

[editor.file-picker]
hidden = false
